import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,readdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const folder=mkdtempSync(join(tmpdir(),'front-verify-'));
const compile=(name,file,replacements=[])=>{let src=readFileSync(file,'utf8');for(const [a,b] of replacements)src=src.replaceAll(a,b);writeFileSync(join(folder,name+'.mjs'),ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);};
compile('domain','lib/domain.ts');compile('providers','lib/providers.ts',[["'./domain'","'./domain.mjs'"]]);compile('narratives','lib/narratives.ts',[["'./domain'","'./domain.mjs'"],["'./providers'","'./providers.mjs'"]]);
compile('route','app/api/desk/route.ts',[["import {env} from 'cloudflare:workers';","const env=globalThis.testEnv;"],["import {getChatGPTUser} from '@/app/chatgpt-auth';","const getChatGPTUser=async()=>globalThis.testUser;"],["'@/lib/providers'","'./providers.mjs'"],["'@/lib/domain'","'./domain.mjs'"],["'@/lib/narratives'","'./narratives.mjs'"]]);
const d=await import(pathToFileURL(join(folder,'domain.mjs')));const p=await import(pathToFileURL(join(folder,'providers.mjs')));
const mint='So11111111111111111111111111111111111111112';
const mk=(liq,source)=>({mint,name:'Token',symbol:'T',price:1,liquidity:liq,volume:1,change:0,created:null,url:'https://dexscreener.com/solana/test',sources:[source],socials:[]});
assert.equal(d.mergeCoins([mk(100,'A'),mk(200,'B')]).length,1);assert.equal(d.mergeCoins([mk(100,'A'),mk(200,'B')])[0].liquidity,200);assert.deepEqual(d.mergeCoins([mk(100,'A'),mk(200,'B')])[0].sources,['A','B']);assert.equal(d.safeUrl('javascript:alert(1)'),'');assert.equal(d.mergeCoins([{...mk(1,'A'),mint:'invalid'}]).length,0);
const f=d.openFill(100,2),c=d.closeFill(f.quantity,2);assert(c.proceeds<100&&c.proceeds>97);assert.throws(()=>d.openFill(-1,2));assert.throws(()=>d.openFill(100,0));assert.throws(()=>d.closeFill(1,NaN));assert(d.batches(Array.from({length:150},(_,i)=>'account_'+i)).every(g=>g.map(a=>'from:'+a).join(' OR ').length<=450));
const database=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')))database.exec(readFileSync('drizzle/'+file,'utf8'));
function prep(sql,args=[]){return{bind:(...a)=>prep(sql,a),first:async()=>database.prepare(sql).get(...args)??null,all:async()=>({results:database.prepare(sql).all(...args)}),run:async()=>database.prepare(sql).run(...args)};}
globalThis.testEnv={DB:{prepare:prep,batch:async(stmts)=>{database.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());database.exec('COMMIT');return r;}catch(e){database.exec('ROLLBACK');throw e;}}},FRONT_SETTINGS_KEY:Buffer.alloc(32,7).toString('base64')};
globalThis.testUser={userId:'alice'};
const originalFetch=globalThis.fetch;
globalThis.fetch=async url=>{if(String(url).includes('geckoterminal'))return new Response('rate limit',{status:429});return Response.json([{chainId:'solana',baseToken:{address:mint,name:'Token',symbol:'T'},priceUsd:'2',liquidity:{usd:100000},volume:{h24:300},priceChange:{h24:2},url:'https://dexscreener.com/solana/test'}]);};
const partial=await p.searchCoins('token');assert(partial.coverage.some(x=>!x.ok));assert(partial.coins.length===1);
const r=await import(pathToFileURL(join(folder,'route.mjs')));
const post=(body,origin='https://test.local')=>r.POST(new Request('https://test.local/api/desk',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
const get=()=>r.GET(new Request('https://test.local/api/desk?action=state'));
assert.equal((await post({action:'watch',mint,name:'Token'},'https://evil.test')).status,403);
assert.equal((await post({action:'watch',mint,name:'Token'})).status,200);assert.equal((await (await get()).json()).watch.length,1);
const id='01234567-0123-4123-8123-012345678901';assert.equal((await post({action:'open',mint,amount:100,id})).status,200);await post({action:'open',mint,amount:100,id});assert.equal((await (await get()).json()).trades.length,1);
globalThis.testUser={userId:'bob'};assert.equal((await (await get()).json()).watch.length,0);assert.equal((await post({action:'close',id})).status,404);await post({action:'unwatch',mint});
globalThis.testUser={userId:'alice'};assert.equal((await (await get()).json()).watch.length,1);await post({action:'close',id});const firstClose=(await (await get()).json()).trades[0];await post({action:'close',id});const secondClose=(await (await get()).json()).trades[0];assert.deepEqual(firstClose,secondClose);assert(firstClose.proceeds<firstClose.amount);
assert.equal((await post({action:'settings',token:'test-secret',accounts:'account_one,account_two'})).status,200);const row=database.prepare('SELECT * FROM settings').get();assert(!row.secret.includes('test-secret'));assert(!(await (await get()).text()).includes('test-secret'));assert.equal((await post({action:'disconnect'})).status,200);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM settings').get().n,0);
globalThis.testUser=null;assert.equal((await get()).status,401);assert.equal((await post({action:'watch',mint,name:'Token'})).status,401);
globalThis.fetch=originalFetch;database.close();rmSync(folder,{recursive:true,force:true});console.log('PASS: mint deduplication, source failures, execution costs, invalid quotes, account batching, migrations, auth, CSRF, owner isolation, idempotent orders, encrypted settings and disconnect.');
