import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,readdirSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const folder=mkdtempSync(join('node_modules','.front-verify-'));
const compile=(name,file,replacements=[])=>{let src=readFileSync(file,'utf8');for(const [a,b] of replacements)src=src.replaceAll(a,b);writeFileSync(join(folder,name+'.mjs'),ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);};
compile('domain','lib/domain.ts');compile('schemas','lib/schemas.ts');compile('providers','lib/providers.ts',[["'./domain'","'./domain.mjs'"],["'./schemas'","'./schemas.mjs'"]]);compile('pumpfun','lib/pumpfun.ts');compile('narratives-base','lib/narratives-base.ts',[["'./domain'","'./domain.mjs'"],["'./providers'","'./providers.mjs'"],["'./schemas'","'./schemas.mjs'"]]);compile('narratives','lib/narratives.ts',[["'./narratives-base'","'./narratives-base.mjs'"],["'./pumpfun'","'./pumpfun.mjs'"]]);compile('request-origin','lib/request-origin.ts');
compile('route','app/api/desk/route.ts',[["import {env} from 'cloudflare:workers';","const env=globalThis.testEnv;"],["import {getChatGPTUser} from '@/app/chatgpt-auth';","const getChatGPTUser=async()=>globalThis.testUser;"],["'@/lib/providers'","'./providers.mjs'"],["'@/lib/domain'","'./domain.mjs'"],["'@/lib/narratives'","'./narratives.mjs'"],["'@/lib/request-origin'","'./request-origin.mjs'"]]);
const d=await import(pathToFileURL(join(folder,'domain.mjs')));const p=await import(pathToFileURL(join(folder,'providers.mjs')));const n=await import(pathToFileURL(join(folder,'narratives.mjs')));
const mint='So11111111111111111111111111111111111111112';
const mk=(liq,source)=>({mint,name:'Token',symbol:'T',price:1,liquidity:liq,volume:1,change:0,created:null,url:'https://dexscreener.com/solana/test',sources:[source],socials:[]});
assert.equal(d.mergeCoins([mk(100,'A'),mk(200,'B')]).length,1);assert.equal(d.mergeCoins([mk(100,'A'),mk(200,'B')])[0].liquidity,200);assert.deepEqual(d.mergeCoins([mk(100,'A'),mk(200,'B')])[0].sources,['A','B']);assert.equal(d.safeUrl('javascript:alert(1)'),'');assert.equal(d.mergeCoins([{...mk(1,'A'),mint:'invalid'}]).length,0);
const f=d.openFill(100,2),c=d.closeFill(f.quantity,2);assert(c.proceeds<100&&c.proceeds>97);assert.throws(()=>d.openFill(-1,2));assert.throws(()=>d.openFill(100,0));assert.throws(()=>d.closeFill(1,NaN));assert(d.batches(Array.from({length:150},(_,i)=>'account_'+i)).every(g=>g.map(a=>'from:'+a).join(' OR ').length<=450));
assert.equal(n.isBroadNarrativeTitle('crypto'),true);assert.equal(n.isBroadNarrativeTitle('viral meme'),true);assert.equal(n.isBroadNarrativeTitle('Dejon Love'),false);assert.equal(n.narrativeTitleSimilarity('Dejon Love','DejonLove'),1);assert.equal(n.lifecycleStage(Date.now()-49*3600000,0,0,0),'Archived');
const database=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())database.exec(readFileSync('drizzle/'+file,'utf8'));
function prep(sql,args=[]){return{bind:(...a)=>prep(sql,a),first:async()=>database.prepare(sql).get(...args)??null,all:async()=>({results:database.prepare(sql).all(...args)}),run:async()=>database.prepare(sql).run(...args)};}
globalThis.testEnv={DB:{prepare:prep,batch:async(stmts)=>{database.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());database.exec('COMMIT');return r;}catch(e){database.exec('ROLLBACK');throw e;}}},FRONT_SETTINGS_KEY:Buffer.alloc(32,7).toString('base64')};
globalThis.testUser={userId:'alice'};
const originalFetch=globalThis.fetch;
globalThis.fetch=async url=>{if(String(url).includes('geckoterminal'))return new Response('rate limit',{status:429});return Response.json([{chainId:'solana',baseToken:{address:mint,name:'Token',symbol:'T'},priceUsd:'2',liquidity:{usd:100000},volume:{h24:300},priceChange:{h24:2},url:'https://dexscreener.com/solana/test'}]);};
const partial=await p.searchCoins('token');assert(partial.coverage.some(x=>!x.ok));assert(partial.coins.length===1);
assert.equal(p.dexCoins([{chainId:'solana',baseToken:{address:mint,name:'T',symbol:'T'},priceUsd:'2',surprise:{new:'field'}},'garbage',null]).length,1);
assert.equal(p.dexCoins({pairs:[{chainId:'solana',baseToken:{address:mint}}]}).length,1);
assert.equal(p.dexCoins([{chainId:'ethereum',baseToken:{address:mint}}]).length,0);
assert.throws(()=>p.dexCoins('nope'),/unexpected response shape/);
assert.equal(p.geckoCoins({data:[{attributes:{address:'pool',name:'A / B'}}]})[0].name,'A');
assert.equal(p.geckoCoins({data:[{}]})[0].name,'Unknown');
assert.throws(()=>p.geckoCoins(42),/unexpected response shape/);

await n.saveEvidence(globalThis.testEnv.DB,'alice',{id:'x:raw1',platform:'X',author:'a',url:'https://x.com/a/status/999',content:'Breaking News #Crypto meme',published:Date.now(),views:null,likes:null,provenance:'test'});assert.equal(database.prepare('SELECT COUNT(*) AS n FROM narratives').get().n,0,'raw evidence must not auto-create broad narratives');
const now=Date.now();for(let i=0;i<65;i++){const id=`auto:topic-${i}`;database.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?)').run('alice',id,`Niche Topic ${i}`,JSON.stringify([`Niche Topic ${i}`]),now);const evidence=`x:p${i}`;database.prepare('INSERT INTO evidence(owner,id,platform,author,url,content,published,first_seen,last_seen,provenance) VALUES(?,?,?,?,?,?,?,?,?,?)').run('alice',evidence,'X',`author${i}`,`https://x.com/a/status/${1000+i}`,`Niche Topic ${i} reaction`,now,now,now,'test');database.prepare('INSERT INTO evidence_links(owner,narrative,evidence,reason) VALUES(?,?,?,?)').run('alice',id,evidence,'test');}
let feed=await n.narrativeFeed(globalThis.testEnv.DB,'alice',{limit:50});assert.equal(feed.cards.length,50);assert.equal(feed.page.total,65);assert.equal(feed.page.hasMore,true);assert.equal(feed.page.nextOffset,50);feed=await n.narrativeFeed(globalThis.testEnv.DB,'alice',{limit:50,offset:50});assert.equal(feed.cards.length,15);assert.equal(feed.page.hasMore,false);
database.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?)').run('alice','auto:crypto','Crypto',JSON.stringify(['Crypto']),now-600000);database.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?)').run('alice','manual:crypto','Crypto',JSON.stringify(['Crypto']),now-600000);const cleaned=await n.cleanupLegacyNarratives(globalThis.testEnv.DB,'alice');assert(cleaned.deletedBroad>=1);assert.equal(database.prepare("SELECT COUNT(*) AS n FROM narratives WHERE id='auto:crypto'").get().n,0);assert.equal(database.prepare("SELECT COUNT(*) AS n FROM narratives WHERE id='manual:crypto'").get().n,1,'manual narratives must survive cleanup');
const mergeA='auto:banana-phone-kid',mergeB='auto:banana phone kid';database.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?)').run('alice',mergeA,'Banana Phone Kid',JSON.stringify(['Banana Phone Kid']),now);database.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?)').run('alice',mergeB,'BananaPhoneKid',JSON.stringify(['BananaPhoneKid']),now);for(const [idx,eid] of ['x:dup1','x:dup2'].entries()){database.prepare('INSERT INTO evidence(owner,id,platform,author,url,content,published,first_seen,last_seen,provenance) VALUES(?,?,?,?,?,?,?,?,?,?)').run('alice',eid,'X',`dup${idx}`,`https://x.com/a/status/${2000+idx}`,'Banana Phone Kid reaction',now,now,now,'test');database.prepare('INSERT INTO evidence_links(owner,narrative,evidence,reason) VALUES(?,?,?,?)').run('alice',mergeA,eid,'test');database.prepare('INSERT INTO evidence_links(owner,narrative,evidence,reason) VALUES(?,?,?,?)').run('alice',mergeB,eid,'test');}const deduped=await n.cleanupLegacyNarratives(globalThis.testEnv.DB,'alice');assert(deduped.mergedDuplicates>=1);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM narratives WHERE id IN (?,?)').get(mergeA,mergeB).n,1);

const r=await import(pathToFileURL(join(folder,'route.mjs')));
const post=(body,origin='https://test.local')=>r.POST(new Request('https://test.local/api/desk',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
const get=()=>r.GET(new Request('https://test.local/api/desk?action=state'));
assert.equal((await post({action:'watch',mint,name:'Token'},'https://evil.test')).status,403);
assert.equal((await post({action:'watch',mint,name:'Token'})).status,200);assert.equal((await (await get()).json()).watch.length,1);
const id='01234567-0123-4123-8123-012345678901';assert.equal((await post({action:'open',mint,amount:100,id})).status,200);await post({action:'open',mint,amount:100,id});assert.equal((await (await get()).json()).trades.length,1);
globalThis.testUser={userId:'bob'};assert.equal((await (await get()).json()).watch.length,0);assert.equal((await post({action:'close',id})).status,404);await post({action:'unwatch',mint});
globalThis.testUser={userId:'alice'};assert.equal((await (await get()).json()).watch.length,1);await post({action:'close',id});const firstClose=(await (await get()).json()).trades[0];await post({action:'close',id});const secondClose=(await (await get()).json()).trades[0];assert.deepEqual(firstClose,secondClose);assert(firstClose.proceeds<firstClose.amount);
globalThis.testUser={userId:'bob'};assert.equal((await post({action:'open',mint,amount:100,id})).status,200);assert.equal((await (await get()).json()).trades.length,1,'bob\'s paper buy must record even when alice used the same id');globalThis.testUser={userId:'alice'};assert.equal((await (await get()).json()).trades.length,1);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM trades').get().n,2);
assert.equal((await post({action:'settings',token:'test-secret',accounts:'account_one,account_two'})).status,200);const row=database.prepare('SELECT * FROM settings').get();assert(!row.secret.includes('test-secret'));assert(!(await (await get()).text()).includes('test-secret'));assert.equal((await post({action:'disconnect'})).status,200);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM settings').get().n,0);
globalThis.testUser=null;assert.equal((await get()).status,401);assert.equal((await post({action:'watch',mint,name:'Token'})).status,401);
globalThis.fetch=originalFetch;database.close();rmSync(folder,{recursive:true,force:true});console.log('PASS: mint deduplication, source failures, execution costs, invalid quotes, account batching, migrations, auth, CSRF, owner isolation, per-owner trade ids, provider payload validation, idempotent orders, encrypted settings, narrative promotion gate, pagination, lifecycle, cleanup and duplicate merge.');