'use client';

import { useEffect, useState } from 'react';
import { Activity, ExternalLink, Layers, RefreshCw, Sparkles, TrendingUp } from 'lucide-react';
import styles from './discovery-dashboard.module.css';

type PublicItem={id:string;source:string;sourceKey:string;title:string;url:string;observed:number;published:number|null;views:number|null;likes:number|null;status:'Raw signal'|'Early candidate'|'Promoted';detail:string};
type PublicDiagnostics={browserEvidence:number;usableBrowserEvidence?:number;ignoredNotifications?:number;ignoredJunk?:number;uniqueAuthors:number;sourceCounts:Record<string,number>;latestBrowserSeen:number|null;diagnosis:string|null};
type PublicFeed={items:PublicItem[];page:{total:number};diagnostics:PublicDiagnostics};
type RadarSignal={id:string;title:string;detail:string;url:string};
type RadarFeed={signals:RadarSignal[];page?:{total:number}};
type MomentumWindow={creatorDelta:number;evidenceDelta:number;platformDelta:number;creatorGrowthPct:number|null};
type Momentum={label:'New'|'Accelerating'|'Rising'|'Steady'|'Cooling';score:number;creatorDelta:number;evidenceDelta:number;creatorGrowthPct:number|null;windows?:Record<string,MomentumWindow>};
type Topic={key:string;title:string;observed:number;tier:string;score:number;momentum:Momentum;creators:number;evidenceCount:number;platforms:string[];origin:{url:string;published:number|null}|null;aliases:string[]};
type Launch={mint:string;name:string;symbol:string|null;seen:number;narrative:string|null;match_type:string;data:{narrativeTitle?:string}};
type Intel={topics:Topic[];launches:Launch[];queue:Record<string,number>;at:number};
type BridgeTopic={topic:string;key:string;authorCount:number;evidenceCount:number;platforms:string[];tier?:string;score?:number;originCandidate?:{url:string;published:number|null};momentum?:Momentum;anchors?:{url:string;content:string;author:string;platform:string}[]};
type BridgeAudit={sourceCounts?:Record<string,number>;uniqueEvidence?:number;acceleratingTopics?:number;errors?:number};
type BridgeHealth={ok:boolean;version:number;running:boolean;lastRun:number|null;lastCount:number;lastError:string|null;pendingCount?:number;scanConnection?:string;lastTopics?:BridgeTopic[];lastAudit?:BridgeAudit;topicHistoryCount?:number};

const BRIDGE='http://127.0.0.1:43981';
const sourceLabels:Record<string,string>={'x-trending':'X Trending','x-feed':'X Feed','x-search':'X Search','tiktok-trending':'TikTok Trending','tiktok-explore':'TikTok Explore','tiktok-search':'TikTok Search','google-trends':'Google Trends','market-theme':'Market themes'};
const age=(ts:number|null|undefined)=>{if(!ts)return'unknown';const mins=Math.max(0,Math.round((Date.now()-ts)/60000));if(mins<60)return`${mins}m`;const h=mins/60;if(h<48)return`${h.toFixed(h<10?1:0)}h`;return`${Math.round(h/24)}d`;};
const compact=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
const norm=(v:string)=>v.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
async function getJson<T>(url:string):Promise<T>{const r=await fetch(url,{cache:'no-store'});const d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}

export default function DiscoveryDashboard(){
 const [publicFeed,setPublicFeed]=useState<PublicFeed|null>(null),[radar,setRadar]=useState<RadarFeed|null>(null),[intel,setIntel]=useState<Intel|null>(null),[bridge,setBridge]=useState<BridgeHealth|null>(null),[bridgeReachable,setBridgeReachable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){
  setBusy(true);setError('');
  const [publicResult,radarResult,intelResult]=await Promise.allSettled([getJson<PublicFeed>('/api/public-signals?limit=80&source=all'),getJson<RadarFeed>('/api/desk?action=discover&limit=100&offset=0'),getJson<Intel>('/api/topic-intel')]);
  if(publicResult.status==='fulfilled')setPublicFeed(publicResult.value);else setError(publicResult.reason instanceof Error?publicResult.reason.message:'Could not load source signals.');
  if(radarResult.status==='fulfilled')setRadar(radarResult.value);else setError(old=>old||(radarResult.reason instanceof Error?radarResult.reason.message:'Could not load Narrative Radar.'));
  if(intelResult.status==='fulfilled')setIntel(intelResult.value);else setError(old=>old||(intelResult.reason instanceof Error?intelResult.reason.message:'Could not load topic history.'));
  try{const health=await getJson<BridgeHealth>(BRIDGE+'/health');setBridge(health);setBridgeReachable(true);}catch{setBridgeReachable(false);setBridge(null);}setBusy(false);
 }
 useEffect(()=>{const t=window.setTimeout(()=>void refresh(),0),id=window.setInterval(()=>void refresh(),45000),onSaved=()=>void refresh();window.addEventListener('front-browser-evidence-saved',onSaved);return()=>{window.clearTimeout(t);window.clearInterval(id);window.removeEventListener('front-browser-evidence-saved',onSaved);};},[]);
 const diag=publicFeed?.diagnostics,radarSignals=radar?.signals??[],radarTitles=new Set(radarSignals.map(x=>norm(x.title))),persisted=intel?.topics??[];
 const bridgeTopics:Topic[]=(bridge?.lastTopics??[]).map((t)=>({key:t.key,title:t.topic,observed:bridge?.lastRun??Date.now(),tier:t.tier||'candidate',score:t.score||0,momentum:t.momentum||{label:'New',score:0,creatorDelta:0,evidenceDelta:0,creatorGrowthPct:null},creators:t.authorCount,evidenceCount:t.evidenceCount,platforms:t.platforms,origin:t.originCandidate?.url?{url:t.originCandidate.url,published:t.originCandidate.published??null}:null,aliases:[t.topic]}));
 const topicMap=new Map<string,Topic>();for(const topic of persisted)topicMap.set(norm(topic.key||topic.title),topic);for(const topic of bridgeTopics){const key=norm(topic.key||topic.title),old=topicMap.get(key);if(!old||topic.observed>=old.observed)topicMap.set(key,topic);}const topics=[...topicMap.values()].sort((a,b)=>(b.momentum?.score||0)-(a.momentum?.score||0)||b.score-a.score).slice(0,30);
 const raw=(publicFeed?.items??[]).filter(x=>x.status==='Raw signal').slice(0,14),latest=bridge?.lastRun||diag?.latestBrowserSeen||intel?.at||null,pending=bridge?.pendingCount??0,quality=diag?.browserEvidence?Math.round(100*((diag.usableBrowserEvidence??diag.browserEvidence)/diag.browserEvidence)):0,radarCount=radar?.page?.total??radarSignals.length,preBreakout=topics.filter(x=>x.tier==='pre-breakout').length,accelerating=topics.filter(x=>x.momentum?.label==='Accelerating').length;
 return <section className={styles.shell} aria-label="Front discovery dashboard">
  <header className={styles.header}><div className={styles.brand}><span className={styles.mark}><Layers size={18}/></span><span>FRONT <small>NARRATIVE INTELLIGENCE</small></span></div><div className={styles.headerActions}><span className={styles.status}><span className={bridgeReachable?(bridge?.running?styles.dotBusy:styles.dot):styles.dotOff}/>{bridgeReachable?`Scanner ${bridge?.running?'running':'connected'}`:'Scanner offline'}</span><button className={styles.button} onClick={()=>void refresh()} disabled={busy}><RefreshCw size={14} className={busy?styles.spin:''}/>Refresh</button></div></header>
  <main className={styles.main}>
   <div className={styles.hero}><div><div className={styles.eyebrow}>ONE DASHBOARD · EVIDENCE → PRE-BREAKOUT → MOMENTUM → RADAR → COIN</div><h1>Find the narrative before the market does.</h1><p>Front keeps raw social evidence separate from actual topics, then ranks repeated narratives by creator growth, cross-platform spread, freshness and momentum.</p></div><span className={styles.status}>Last scan {latest?`${age(latest)} ago`:'not yet'}</span></div>
   {error&&<div className={styles.alert}>{error}</div>}{diag?.diagnosis&&<div className={styles.info}>{diag.diagnosis}</div>}
   <div className={styles.stats}><div className={styles.stat}><span>Detected topics</span><strong>{topics.length}</strong><small>{preBreakout} pre-breakout</small></div><div className={styles.stat}><span>Accelerating</span><strong>{accelerating}</strong><small>multi-scan momentum</small></div><div className={styles.stat}><span>Narrative Radar</span><strong>{radarCount}</strong><small>promoted narratives</small></div><div className={styles.stat}><span>Evidence quality</span><strong>{diag?.browserEvidence?`${quality}%`:'—'}</strong><small>{(diag?.ignoredNotifications??0)+(diag?.ignoredJunk??0)} junk rejected</small></div></div>
   <div className={styles.funnel}><b>{diag?.browserEvidence??0}</b> collected <span className={styles.arrow}>→</span><b>{diag?.usableBrowserEvidence??0}</b> usable <span className={styles.arrow}>→</span><b>{topics.length}</b> topics <span className={styles.arrow}>→</span><b>{radarCount}</b> radar <span className={styles.arrow}>→</span><b>{intel?.queue?.queued??0}</b> coin checks queued</div>
   <div className={styles.grid}><div className={styles.column}>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2><TrendingUp size={16}/> Narrative stream</h2><p>One ranked stream. Pre-breakout is intentionally earlier and noisier; Radar means the stronger promotion gate has been crossed.</p></div><span className={styles.count}>{topics.length} active</span></div><div className={styles.list}>{topics.map((topic,i)=>{const radarHit=radarTitles.has(norm(topic.title)),hour=topic.momentum?.windows?.['60'];return <article className={styles.item} key={`${topic.key}:${i}`}><span className={styles.rank}>{String(i+1).padStart(2,'0')}</span><div><div className={styles.badges}><span className={radarHit?styles.badgeRadar:topic.momentum?.label==='Accelerating'?styles.badgeHot:topic.tier==='pre-breakout'?styles.badgeRaw:styles.badge}>{radarHit?'Radar':topic.tier==='pre-breakout'?'Pre-breakout':topic.momentum?.label||'Candidate'}</span><span className={styles.badge}>{topic.creators} creators</span><span className={styles.badge}>{topic.platforms.join(' + ')||'social'}</span><span className={styles.badge}>{age(topic.origin?.published||topic.observed)}</span></div><h3>{topic.title}</h3><p>{topic.evidenceCount} supporting posts{hour?` · 1h creators ${hour.creatorDelta>=0?'+':''}${hour.creatorDelta}`:''}{hour?.creatorGrowthPct!=null?` · ${hour.creatorGrowthPct}% 1h growth`:''} · momentum {topic.momentum?.score?.toFixed?.(1)??0}</p>{topic.origin&&<div className={styles.meta}>Earliest sampled evidence: {age(topic.origin.published)} ago</div>}</div>{topic.origin&&<a className={styles.link} href={topic.origin.url} target="_blank" rel="noreferrer" aria-label={`Open earliest evidence for ${topic.title}`}><ExternalLink size={14}/></a>}</article>;})}{!topics.length&&<div className={styles.empty}>No repeated topic has cleared the pre-breakout gate yet. Run a fresh deep scan; isolated posts stay evidence instead of being mislabeled as topics.</div>}</div></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2><Sparkles size={16}/> Source pulse</h2><p>Raw trend surfaces stay visible here as discovery seeds, but they do not become narratives by themselves.</p></div><span className={styles.count}>{publicFeed?.page.total??0} signals</span></div><div className={styles.list}>{raw.map((item,i)=><article className={styles.item} key={item.id}><span className={styles.rank}>{String(i+1).padStart(2,'0')}</span><div><div className={styles.badges}><span className={styles.badgeRaw}>Raw</span><span className={styles.badge}>{item.source}</span></div><h3>{item.title}</h3><p>{item.detail}</p><div className={styles.meta}>views {compact(item.views)} · likes {compact(item.likes)}</div></div><a className={styles.link} href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a></article>)}{!raw.length&&<div className={styles.empty}>No raw trend signals are synced yet.</div>}</div></section>
   </div><aside className={styles.column}><section className={styles.panel}><div className={styles.panelHead}><div><h2><Activity size={16}/> System health</h2><p>Everything needed to judge whether Front is actually working.</p></div></div><div className={styles.health}><div className={styles.healthRow}><span>Bridge</span><strong>{bridgeReachable?`v${bridge?.version} · ${bridge?.scanConnection||'connected'}`:'offline'}</strong></div><div className={styles.healthRow}><span>Last scan rows</span><strong>{bridge?.lastCount??diag?.browserEvidence??0}</strong></div><div className={styles.healthRow}><span>Pending sync</span><strong>{pending}</strong></div><div className={styles.healthRow}><span>Unique creators</span><strong>{diag?.uniqueAuthors??0}</strong></div><div className={styles.healthRow}><span>Snapshot history</span><strong>{bridge?.topicHistoryCount??persisted.length}</strong></div><div className={styles.healthRow}><span>Coin queue</span><strong>{(intel?.queue?.queued??0)} queued · {(intel?.queue?.done??0)} done</strong></div><div className={styles.healthRow}><span>24/7 launch watcher</span><strong>{intel?'server-backed':'unknown'}</strong></div><div className={styles.progress}><span style={{width:`${Math.max(0,Math.min(100,quality))}%`}}/></div>{bridge?.lastError&&<div className={styles.alert}><b>Scanner warning:</b> {bridge.lastError}</div>}</div><div className={styles.quality}><h3>Evidence by source</h3><div className={styles.sourceGrid}>{Object.entries(diag?.sourceCounts??{}).sort((a,b)=>b[1]-a[1]).map(([key,count])=><div className={styles.sourceCard} key={key}><span>{sourceLabels[key]||key}</span><b>{count}</b></div>)}</div></div>{(intel?.launches?.length??0)>0&&<div className={styles.quality}><h3>Recent launch matches</h3>{intel!.launches.slice(0,5).map((hit)=><div className={styles.healthRow} key={hit.mint}><span>{hit.name}{hit.symbol?` · ${hit.symbol}`:''}</span><strong>{hit.data?.narrativeTitle||hit.match_type}</strong></div>)}</div>}<div className={styles.footerNote}>Topic snapshots persist on the server. PumpPortal matching runs in the standalone server process and uses creation events only. The local authenticated browser is still required for X/TikTok collection.</div></section></aside></div>
  </main>
 </section>;
}
