'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ExternalLink, Layers, Radio, RefreshCw, Sparkles, TrendingUp } from 'lucide-react';
import styles from './discovery-dashboard.module.css';

type PublicStatus='Raw signal'|'Early candidate'|'Promoted';
type PublicItem={id:string;source:string;sourceKey:string;title:string;query:string;url:string;observed:number;published:number|null;views:number|null;likes:number|null;status:PublicStatus;narrative?:{id:string;title:string}|null;detail:string};
type PublicDiagnostics={browserEvidence:number;usableBrowserEvidence?:number;ignoredNotifications?:number;ignoredJunk?:number;evidenceOnly?:number;explicitTopicSignals?:number;uniqueAuthors:number;earlyCandidates:number;sourceCounts:Record<string,number>;latestBrowserSeen:number|null;externalSignals:number;diagnosis:string|null};
type PublicFeed={items:PublicItem[];page:{total:number};counts:Record<string,number>;diagnostics:PublicDiagnostics;at:number;note:string};
type RadarSignal={id:string;title:string;source:string;detail:string;url:string;query:string};
type RadarFeed={signals:RadarSignal[];page?:{total:number};at:number;note?:string};
type Momentum={label:'New'|'Accelerating'|'Rising'|'Steady'|'Cooling';score:number;creatorDelta:number;evidenceDelta:number;platformDelta:number;creatorGrowthPct:number|null;newTopic:boolean;comparedAt:number|null};
type BridgeTopic={topic:string;key:string;authorCount:number;evidenceCount:number;platforms:string[];specificityScore?:number;score?:number;anchors?:{url:string;content:string;author:string;platform:string}[];momentum?:Momentum;detector?:string};
type BridgeAudit={sourceCounts?:Record<string,number>;collected?:number;uniqueEvidence?:number;inferredTopics?:number;acceleratingTopics?:number;newTopics?:number;errors?:number};
type BridgeHealth={ok:boolean;version:number;running:boolean;lastRun:number|null;lastCount:number;lastError:string|null;pendingCount?:number;nextScheduledRun?:number|null;scanConnection?:string;lastTopics?:BridgeTopic[];lastAudit?:BridgeAudit;topicHistoryCount?:number};

const BRIDGE='http://127.0.0.1:43981';
const sourceLabels:Record<string,string>={'x-trending':'X Trending','x-feed':'X Feed','x-search':'X Search','tiktok-trending':'TikTok Trending','tiktok-explore':'TikTok Explore','tiktok-search':'TikTok Search','google-trends':'Google Trends','market-theme':'Market themes','x-browser':'X Browser','tiktok-browser':'TikTok Browser'};
const age=(ts:number|null|undefined)=>{if(!ts)return'unknown';const mins=Math.max(0,Math.round((Date.now()-ts)/60000));if(mins<60)return`${mins}m`;const h=mins/60;if(h<48)return`${h.toFixed(h<10?1:0)}h`;return`${Math.round(h/24)}d`;};
const compact=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{cache:'no-store',...init});const d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}

export default function DiscoveryDashboard(){
 const [publicFeed,setPublicFeed]=useState<PublicFeed|null>(null),[radar,setRadar]=useState<RadarFeed|null>(null),[bridge,setBridge]=useState<BridgeHealth|null>(null),[bridgeReachable,setBridgeReachable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState<'all'|'early'|'raw'>('all');
 async function refresh(){setBusy(true);setError('');const [publicResult,radarResult]=await Promise.allSettled([json<PublicFeed>('/api/public-signals?limit=100&source=all'),json<RadarFeed>('/api/desk?action=discover&limit=100&offset=0')]);if(publicResult.status==='fulfilled')setPublicFeed(publicResult.value);else setError(publicResult.reason instanceof Error?publicResult.reason.message:'Could not load Public Signals.');if(radarResult.status==='fulfilled')setRadar(radarResult.value);else setError(old=>old||(radarResult.reason instanceof Error?radarResult.reason.message:'Could not load Narrative Radar.'));try{const health=await json<BridgeHealth>(BRIDGE+'/health');setBridge(health);setBridgeReachable(true);}catch{setBridgeReachable(false);setBridge(null);}setBusy(false);}
 useEffect(()=>{const t=window.setTimeout(()=>void refresh(),0),id=window.setInterval(()=>void refresh(),60000),onSaved=()=>void refresh();window.addEventListener('front-browser-evidence-saved',onSaved);return()=>{window.clearTimeout(t);window.clearInterval(id);window.removeEventListener('front-browser-evidence-saved',onSaved);};},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const early=useMemo(()=>publicFeed?.items.filter(x=>x.status==='Early candidate')??[],[publicFeed]),raw=useMemo(()=>publicFeed?.items.filter(x=>x.status==='Raw signal')??[],[publicFeed]),visible=useMemo(()=>view==='early'?early:view==='raw'?raw:(publicFeed?.items??[]),[view,early,raw,publicFeed]);
 const radarCount=radar?.page?.total??radar?.signals.length??0,diag=publicFeed?.diagnostics,quality=diag?.browserEvidence?Math.round(100*((diag.usableBrowserEvidence??diag.browserEvidence)/diag.browserEvidence)):0,latestScan=bridge?.lastRun||diag?.latestBrowserSeen||null,pending=bridge?.pendingCount??0,noData=!busy&&(publicFeed?.items.length??0)===0&&radarCount===0;
 const liveTopics=(bridge?.lastTopics??[]).slice().sort((a,b)=>(b.momentum?.score??0)-(a.momentum?.score??0)||(b.score??0)-(a.score??0)).slice(0,12);
 return <section className={styles.shell} aria-label="Front discovery command center">
  <header className={styles.header}><div className={styles.brand}><span className={styles.mark}><Layers size={18}/></span><span>FRONT <small>DISCOVERY COMMAND CENTER</small></span></div><div className={styles.headerActions}><span className={styles.status}><span className={bridgeReachable?(bridge?.running?styles.dotBusy:styles.dot):styles.dotOff}/>{bridgeReachable?`Scanner ${bridge?.running?'running':'connected'}`:'Scanner offline'}</span><button className={styles.button} onClick={()=>void refresh()} disabled={busy}><RefreshCw size={14} className={busy?styles.spin:''}/>Refresh</button></div></header>
  <main className={styles.main}>
   <div className={styles.hero}><div><div className={styles.eyebrow}>EVIDENCE → CANDIDATE → MOMENTUM → NARRATIVE RADAR</div><h1>See the story before the coin.</h1><p>Front now separates scraped evidence from actual topics, clusters repeated entities and phrases, and compares scans so fast-growing narratives rise before raw popularity alone.</p></div><span className={styles.status}>Last evidence {age(latestScan)}</span></div>
   {error&&<div className={styles.alert}>{error}</div>}{diag?.diagnosis&&<div className={styles.alert}><b>Discovery diagnosis:</b> {diag.diagnosis}</div>}{noData&&<div className={styles.alert}><b>No synced discovery data yet.</b> Run a deep scan with the local bridge and keep Front open long enough to sync the pending queue.</div>}
   <div className={styles.stats}><div className={styles.stat}><span>Public signals</span><strong>{publicFeed?.page.total??'—'}</strong><small>explicit trends + early candidates</small></div><div className={styles.stat}><span>Live topics</span><strong>{liveTopics.length||0}</strong><small>Detection Engine v2</small></div><div className={styles.stat}><span>Narrative Radar</span><strong>{radarCount||0}</strong><small>corroborated niche narratives</small></div><div className={styles.stat}><span>Actual evidence</span><strong>{diag?.usableBrowserEvidence??diag?.browserEvidence??'—'}</strong><small>{(diag?.ignoredNotifications??0)+(diag?.ignoredJunk??0)} junk rows rejected</small></div><div className={styles.stat}><span>Creators</span><strong>{diag?.uniqueAuthors??'—'}</strong><small>unique sampled authors</small></div><div className={styles.stat}><span>History</span><strong>{bridge?.topicHistoryCount??0}</strong><small>scan snapshots for momentum</small></div></div>
   <div className={styles.funnel}><b>{diag?.browserEvidence??0}</b> collected <span className={styles.arrow}>→</span><b>{diag?.usableBrowserEvidence??diag?.browserEvidence??0}</b> evidence <span className={styles.arrow}>→</span><b>{liveTopics.length}</b> detected <span className={styles.arrow}>→</span><b>{radarCount}</b> promoted</div>
   <div className={styles.grid}><div className={styles.column}>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2><TrendingUp size={16}/> Live Topic Momentum</h2><p>These are independently repeated entities/phrases from the latest local scan. Feed captions themselves are never shown as topics.</p></div><span className={styles.count}>{liveTopics.length} detected</span></div><div className={styles.list}>{liveTopics.map((topic,i)=>{const anchor=topic.anchors?.[0];return <article className={styles.item} key={`${topic.key}:${i}`}><span className={styles.rank}>{String(i+1).padStart(2,'0')}</span><div><div className={styles.badges}><span className={topic.momentum?.label==='Accelerating'?styles.badgeHot:styles.badgeRadar}>{topic.momentum?.label||'Detected'}</span><span className={styles.badge}>{topic.authorCount} creators</span><span className={styles.badge}>{topic.platforms.join(' + ')||'social'}</span></div><h3>{topic.topic}</h3><p>{topic.evidenceCount} supporting posts · detector {topic.detector||'niche'}{topic.momentum?.creatorDelta!=null?` · creators ${topic.momentum.creatorDelta>=0?'+':''}${topic.momentum.creatorDelta} vs prior scan`:''}{topic.momentum?.creatorGrowthPct!=null?` · ${topic.momentum.creatorGrowthPct}% growth`:''}</p>{anchor&&<div className={styles.meta}>Evidence: {anchor.platform} @{anchor.author} · {anchor.content.slice(0,150)}</div>}</div>{anchor&&<a className={styles.link} href={anchor.url} target="_blank" rel="noreferrer" aria-label={`Open evidence for ${topic.topic}`}><ExternalLink size={14}/></a>}</article>;})}{!liveTopics.length&&<div className={styles.empty}>{bridgeReachable?'Run a fresh deep scan. A topic appears here only after independent repetition; isolated posts remain evidence.':'Start the local bridge to see scan-level topic momentum.'}</div>}</div></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2><Radio size={16}/> Public Signals + Early Candidates</h2><p>Explicit X/TikTok trend surfaces stay visible while repeated evidence develops into candidates.</p></div><div className={styles.modeBar}>{(['all','early','raw'] as const).map(mode=><button key={mode} className={`${styles.button} ${view===mode?styles.modeActive:''}`} onClick={()=>setView(mode)}>{mode==='all'?'All':mode==='early'?'Early':'Raw'}</button>)}</div></div><div className={styles.list}>{visible.slice(0,30).map((item,i)=><article className={styles.item} key={item.id}><span className={styles.rank}>{String(i+1).padStart(2,'0')}</span><div><div className={styles.badges}><span className={item.status==='Early candidate'?styles.badgeHot:item.status==='Promoted'?styles.badgeRadar:styles.badgeRaw}>{item.status}</span><span className={styles.badge}>{item.source}</span><span className={styles.badge}>{age(item.published||item.observed)}</span></div><h3>{item.title}</h3><p>{item.detail}</p><div className={styles.meta}>views {compact(item.views)} · likes {compact(item.likes)}</div></div><a className={styles.link} href={item.url} target="_blank" rel="noreferrer" aria-label={`Open ${item.title}`}><ExternalLink size={14}/></a></article>)}{!visible.length&&<div className={styles.empty}>No qualifying signals in this view yet.</div>}</div></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h2><Sparkles size={16}/> Narrative Radar</h2><p>Only corroborated niche narratives belong here.</p></div><span className={styles.count}>{radarCount} active</span></div><div className={styles.list}>{(radar?.signals??[]).slice(0,20).map((item,i)=><article className={styles.item} key={item.id}><span className={styles.rank}>{String(i+1).padStart(2,'0')}</span><div><div className={styles.badges}><span className={styles.badgeRadar}>Promoted</span><span className={styles.badge}>Narrative Radar</span></div><h3>{item.title}</h3><p>{item.detail}</p></div><a className={styles.link} href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a></article>)}{!radar?.signals.length&&<div className={styles.empty}>Nothing has crossed the strict promotion gate yet. Watch Live Topic Momentum and Early Candidates instead.</div>}</div></section>
   </div><aside className={styles.column}><section className={styles.panel}><div className={styles.panelHead}><div><h2><Activity size={16}/> Scanner health</h2><p>Collection, cleaning, clustering and momentum diagnostics.</p></div></div><div className={styles.health}><div className={styles.healthRow}><span>Local bridge</span><strong>{bridgeReachable?`v${bridge?.version} · ${bridge?.scanConnection||'connected'}`:'offline / blocked'}</strong></div><div className={styles.healthRow}><span>Last scan</span><strong>{latestScan?`${age(latestScan)} ago`:'none detected'}</strong></div><div className={styles.healthRow}><span>Last scan records</span><strong>{bridge?.lastCount??diag?.browserEvidence??0}</strong></div><div className={styles.healthRow}><span>Pending upload</span><strong>{pending}</strong></div><div className={styles.healthRow}><span>Content quality</span><strong>{diag?.browserEvidence?`${quality}% usable`:'no sample'}</strong></div><div className={styles.healthRow}><span>Accelerating topics</span><strong>{bridge?.lastAudit?.acceleratingTopics??0}</strong></div><div className={styles.progress}><span style={{width:`${Math.max(0,Math.min(100,quality))}%`}}/></div>{bridge?.lastError&&<div className={styles.alert}><b>Last scanner warning:</b> {bridge.lastError}</div>}</div><div className={styles.quality}><h3>Evidence by source</h3><div className={styles.sourceGrid}>{Object.entries(diag?.sourceCounts??{}).sort((a,b)=>b[1]-a[1]).map(([key,count])=><div className={styles.sourceCard} key={key}><span>{sourceLabels[key]||key}</span><b>{count}</b></div>)}{!Object.keys(diag?.sourceCounts??{}).length&&<div className={styles.empty}>No synced browser-source counts yet.</div>}</div></div><div className={styles.footerNote}>Detection Engine v2 keeps a rolling 7-day local topic history. Growth is compared scan-to-scan; raw popularity alone does not determine what rises.</div></section></aside></div>
  </main>
 </section>;
}
