'use client';

import { useEffect, useRef, useState } from 'react';
import { classifyAlias } from '@/lib/coin-matching';
import { coinLinks } from '@/lib/coin-intelligence';
import { ExternalLink, Radio } from 'lucide-react';
import { isPumpPortalCreation, normalizeLaunchName } from '@/lib/live';

type NarrativeCard = { id:string; title:string; aliases:string[]; lastSeen:number };
type Match = { mint:string; name:string; symbol?:string; narrative:string; seen:number; matchConfidence:number; matchReason:string; marketCapSol?:number };
const KEY='front.narrativeCreationMatches.v1';

export default function NarrativeCreationWatcher(){
 const [cards,setCards]=useState<NarrativeCard[]>([]),[matches,setMatches]=useState<Match[]>([]),[status,setStatus]=useState('Connecting');
 const cardsRef=useRef<NarrativeCard[]>([]);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(saved))setMatches(saved.slice(0,20));}catch{}},0);return()=>window.clearTimeout(timer);},[]);
 useEffect(()=>{cardsRef.current=cards;},[cards]);
 useEffect(()=>{let stopped=false;async function load(){try{const r=await fetch('/api/desk?action=narratives',{cache:'no-store'});if(!r.ok)return;const d=await r.json() as {cards?:NarrativeCard[]};if(!stopped)setCards((d.cards||[]).slice(0,50));}catch{}}const kickoff=window.setTimeout(()=>void load(),0);const timer=window.setInterval(load,60000);const refresh=()=>void load();window.addEventListener('front-browser-evidence-saved',refresh);return()=>{stopped=true;window.clearTimeout(kickoff);window.clearInterval(timer);window.removeEventListener('front-browser-evidence-saved',refresh);};},[]);
 useEffect(()=>{let socket:WebSocket|undefined,retry:ReturnType<typeof setTimeout>,stopped=false,attempt=0;const connect=()=>{setStatus('Connecting');socket=new WebSocket('wss://pumpportal.fun/api/data');socket.onopen=()=>{attempt=0;setStatus('Listening');socket?.send(JSON.stringify({method:'subscribeNewToken'}));};socket.onmessage=(event)=>{try{const data=JSON.parse(event.data);if(!isPumpPortalCreation(data)||typeof data.name!=='string')return;const target=normalizeLaunchName(data.name);if(!target)return;let best:{narrative:NarrativeCard;score:number;reason:string}|null=null;for(const narrative of cardsRef.current){for(const term of [narrative.title,...(narrative.aliases||[])]){const hit=classifyAlias(String(data.name),typeof data.symbol==='string'?data.symbol:null,term,narrative.title);if(!hit||!['exact','strong'].includes(hit.type))continue;if(!best||hit.score>best.score)best={narrative,score:hit.score,reason:hit.reason};}}if(!best)return;const marketCapSol=Number.isFinite(Number(data.marketCapSol))?Number(data.marketCapSol):undefined;const hit:Match={mint:data.mint,name:data.name,symbol:typeof data.symbol==='string'?data.symbol:undefined,narrative:best.narrative.title,seen:Date.now(),matchConfidence:Math.round(best.score*100),matchReason:best.reason,marketCapSol};setMatches((old)=>{const next=[hit,...old.filter((x)=>x.mint!==hit.mint)].slice(0,20);localStorage.setItem(KEY,JSON.stringify(next));return next;});if(typeof Notification!=='undefined'&&Notification.permission==='granted')new Notification('NEW MATCHING COIN',{body:`${hit.name} matched “${best.narrative.title}” at ${hit.matchConfidence}% confidence.`});}catch{}};socket.onerror=()=>setStatus('Connection error');socket.onclose=()=>{if(!stopped){setStatus('Reconnecting');retry=setTimeout(connect,Math.min(30000,1000*2**attempt++));}};};const kickoff=window.setTimeout(connect,0);return()=>{stopped=true;window.clearTimeout(kickoff);clearTimeout(retry);socket?.close();};},[]);
 if(!matches.length)return null;
 return <aside style={{position:'fixed',right:20,bottom:78,zIndex:68,width:'min(400px,calc(100vw - 28px))',background:'#101216',color:'#f5f5f5',border:'1px solid #d5ff4855',borderRadius:14,padding:12,boxShadow:'0 18px 50px #0008'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><strong><Radio size={13} style={{display:'inline',verticalAlign:'-2px'}}/> NEW MATCHING COIN</strong><span style={{opacity:.65}}>{status}</span></div>{matches.slice(0,3).map((hit)=>{const links=coinLinks(hit.mint);return <div key={hit.mint} style={{marginTop:9,paddingTop:9,borderTop:'1px solid #ffffff18',display:'grid',gap:4}}><strong>{hit.name}{hit.symbol?` · $${hit.symbol}`:''}</strong><div style={{fontSize:12,opacity:.78}}>{hit.matchConfidence}% match · {hit.narrative}</div><div style={{fontSize:11,opacity:.62}}>{hit.matchReason}</div>{hit.marketCapSol!==undefined&&<div style={{fontSize:12}}>Creation event MC: {hit.marketCapSol.toLocaleString(undefined,{maximumFractionDigits:2})} SOL</div>}<div style={{fontSize:11,opacity:.6}}>Observed {new Date(hit.seen).toLocaleTimeString()} · {hit.mint.slice(0,7)}…{hit.mint.slice(-5)}</div><div style={{fontSize:12,marginTop:4,display:'flex',gap:10,flexWrap:'wrap'}}><a href={links.pumpUrl} target="_blank" rel="noreferrer">Pump.fun <ExternalLink size={11} style={{display:'inline'}}/></a><a href={links.axiomUrl} target="_blank" rel="noreferrer">Axiom <ExternalLink size={11} style={{display:'inline'}}/></a><a href={links.dexScreenerUrl} target="_blank" rel="noreferrer">DexScreener <ExternalLink size={11} style={{display:'inline'}}/></a><button type="button" onClick={()=>void navigator.clipboard?.writeText(hit.mint)} style={{fontSize:12}}>Copy CA</button></div></div>;})}</aside>;
}
