'use client';

import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, ExternalLink, Radio, RefreshCw, Search, X } from 'lucide-react';

type Item={id:string;source:string;sourceKey:string;title:string;query:string;url:string;observed:number;published:number|null;views:number|null;likes:number|null;status:'Raw signal'|'Promoted';narrative?:{id:string;title:string}|null;detail:string};
type Feed={items:Item[];page:{limit:number;offset:number;total:number;hasMore:boolean;nextOffset:number|null};counts:Record<string,number>;at:number;note:string};
const SOURCE_OPTIONS=[['all','All'],['x-trending','X Trending'],['x-feed','X Feed'],['x-search','X Search'],['tiktok-trending','TikTok Trending'],['tiktok-explore','TikTok Explore'],['tiktok-search','TikTok Search'],['google-trends','Google Trends'],['market-theme','Market themes']] as const;
const age=(ts:number|null,observed:number)=>{const base=ts||observed;if(!base)return'age unknown';const mins=Math.max(0,Math.round((Date.now()-base)/60000));if(mins<60)return`${mins}m`;const h=mins/60;if(h<48)return`${h.toFixed(h<10?1:0)}h`;return`${Math.round(h/24)}d`;};
const compact=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);

async function loadFeed(offset:number,source:string,q:string):Promise<Feed>{const p=new URLSearchParams({limit:'50',offset:String(offset),source});if(q.trim())p.set('q',q.trim());const r=await fetch('/api/public-signals?'+p,{cache:'no-store'});const d=await r.json() as Feed&{error?:string};if(!r.ok)throw new Error(d.error||'Could not load public signals.');return d;}

export default function PublicSignalsPanel(){
 const [open,setOpen]=useState(false),[feed,setFeed]=useState<Feed|null>(null),[source,setSource]=useState('all'),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const page=useMemo(()=>feed?Math.floor(feed.page.offset/feed.page.limit)+1:1,[feed]);
 async function refresh(next=offset){setBusy(true);setError('');try{const data=await loadFeed(next,source,query);setFeed(data);setOffset(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!open)return;const t=window.setTimeout(()=>void refresh(0),0);const id=window.setInterval(()=>void refresh(offset),60000);return()=>{window.clearTimeout(t);window.clearInterval(id);};},[open,source]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const handler=()=>{if(open)void refresh(0);};window.addEventListener('front-browser-evidence-saved',handler);return()=>window.removeEventListener('front-browser-evidence-saved',handler);},[open]); // eslint-disable-line react-hooks/exhaustive-deps
 return <>
  <button onClick={()=>setOpen(v=>!v)} aria-label="Open Public Signals" style={{position:'fixed',right:20,top:20,zIndex:75,border:0,borderRadius:999,padding:'12px 16px',fontWeight:800,background:'#d5ff48',color:'#111',boxShadow:'0 10px 30px #0005',cursor:'pointer'}}><Radio size={16} style={{display:'inline',verticalAlign:'-3px',marginRight:7}}/>Public Signals</button>
  {open&&<aside style={{position:'fixed',right:20,top:72,zIndex:74,width:'min(720px,calc(100vw - 28px))',maxHeight:'82vh',overflow:'auto',background:'#101216',color:'#f5f5f5',border:'1px solid #ffffff22',borderRadius:18,padding:18,boxShadow:'0 24px 60px #0009'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><strong>Public Signals</strong><div style={{fontSize:12,opacity:.65}}>Raw discovery feed. Broad trends can appear here without being promoted into Narrative Radar.</div></div><button onClick={()=>setOpen(false)} aria-label="Close" style={{background:'none',border:0,color:'inherit'}}><X/></button></div>
   <div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:12}}>{SOURCE_OPTIONS.map(([key,label])=><button key={key} onClick={()=>{setSource(key);setOffset(0);}} style={{border:'1px solid #ffffff22',borderRadius:999,padding:'6px 9px',background:source===key?'#d5ff48':'#171a20',color:source===key?'#111':'#fff',fontSize:12,cursor:'pointer'}}>{label}{feed?.counts?.[key]!=null&&key!=='all'?` ${feed.counts[key]}`:''}</button>)}</div>
   <div style={{display:'flex',gap:7,marginTop:10}}><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void refresh(0);}} placeholder="Search raw signals…" style={{flex:1,padding:'9px 10px',borderRadius:9,border:'1px solid #ffffff22',background:'#171a20',color:'inherit'}}/><button onClick={()=>void refresh(0)} disabled={busy}><Search size={15}/></button><button onClick={()=>void refresh(offset)} disabled={busy}><RefreshCw size={15}/></button></div>
   {error&&<div style={{marginTop:10,padding:9,borderRadius:9,background:'#ff52521a',fontSize:12}}>{error}</div>}
   <div style={{display:'flex',justifyContent:'space-between',marginTop:12,fontSize:12,opacity:.7}}><span>{feed?`${feed.page.total} signals · page ${page}`:'Loading…'}</span><span>{feed?new Date(feed.at).toLocaleTimeString():''}</span></div>
   {(feed?.items||[]).map(item=><article key={item.id} style={{marginTop:9,padding:11,border:'1px solid #ffffff18',borderRadius:11}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div style={{minWidth:0}}><div style={{display:'flex',gap:6,flexWrap:'wrap',fontSize:11}}><span style={{padding:'2px 6px',borderRadius:999,background:'#ffffff12'}}>{item.source}</span><span style={{padding:'2px 6px',borderRadius:999,background:item.status==='Promoted'?'#d5ff4820':'#ffffff0b',color:item.status==='Promoted'?'#d5ff48':'#bbb'}}>{item.status}</span><span style={{opacity:.6}}>{age(item.published,item.observed)}</span></div><b style={{display:'block',marginTop:5}}>{item.title}</b><div style={{fontSize:12,opacity:.68,marginTop:3}}>{item.detail}</div>{item.narrative&&<div style={{fontSize:12,marginTop:4,color:'#d5ff48'}}>Narrative Radar → {item.narrative.title}</div>}<div style={{fontSize:11,opacity:.55,marginTop:4}}>views {compact(item.views)} · likes {compact(item.likes)}</div></div><a href={item.url} target="_blank" rel="noreferrer" aria-label={`Open ${item.source}`} style={{color:'inherit',flexShrink:0}}><ExternalLink size={16}/></a></div></article>)}
   {feed&&!feed.items.length&&<div style={{padding:24,textAlign:'center',opacity:.6}}>No signals match this source/filter yet. Run a browser scan or clear the filter.</div>}
   {feed&&<div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><button disabled={busy||offset===0} onClick={()=>void refresh(Math.max(0,offset-feed.page.limit))}><ChevronLeft size={14} style={{display:'inline',verticalAlign:'-2px'}}/> Previous</button><button disabled={busy||!feed.page.hasMore} onClick={()=>void refresh(feed.page.nextOffset??offset)}>Next <ChevronRight size={14} style={{display:'inline',verticalAlign:'-2px'}}/></button></div>}
   <small style={{display:'block',opacity:.55,marginTop:10}}>{feed?.note||'X/TikTok browser observations appear here immediately; only corroborated niche narratives are promoted.'}</small>
  </aside>}
 </>;
}
