'use client';

import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Merge, Search, Settings2, Trash2, X } from 'lucide-react';

type Context = { title:string; authorCount:number; evidenceCount:number; platforms:string[]; score:number };
type Card = { id:string; title:string; aliases:string[]; stage:string; authors:number; platforms:string[]; firstSeen:number; lastSeen:number; duplicateIds?:string[]; relatedContexts?:Context[] };
type Page = { limit:number; offset:number; total:number; hasMore:boolean; nextOffset:number|null };
type Feed = { cards:Card[]; page:Page; note?:string };
type ApiError = { error?:string };
type CleanupResult = { deletedBroad?:number; deletedUnsupported?:number; mergedDuplicates?:number };

async function getFeed(offset:number,query:string,archived:boolean,duplicates:boolean):Promise<Feed>{
  const p=new URLSearchParams({action:'narratives',limit:'50',offset:String(offset)});if(query.trim())p.set('q',query.trim());if(archived)p.set('archived','1');if(duplicates)p.set('duplicates','1');
  const r=await fetch('/api/desk?'+p,{cache:'no-store'});const d=await r.json() as Feed&ApiError;if(!r.ok)throw new Error(d.error||'Could not load narratives.');return d;
}
async function mutate<T extends Record<string,unknown>=Record<string,unknown>>(action:string,body:Record<string,unknown>={}):Promise<T>{const r=await fetch('/api/desk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const d=await r.json() as T&ApiError;if(!r.ok)throw new Error(d.error||'Request failed.');return d;}

export default function RadarManager(){
 const [open,setOpen]=useState(false),[feed,setFeed]=useState<Feed|null>(null),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[archived,setArchived]=useState(false),[duplicates,setDuplicates]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[mergeFrom,setMergeFrom]=useState<Card|null>(null);
 const pageNumber=useMemo(()=>feed?Math.floor(feed.page.offset/feed.page.limit)+1:1,[feed]);
 async function load(nextOffset=offset){setBusy('load');setError('');try{setFeed(await getFeed(nextOffset,query,archived,duplicates));setOffset(nextOffset);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 useEffect(()=>{if(!open)return;const id=window.setTimeout(()=>void load(0),0);return()=>window.clearTimeout(id);},[open,archived,duplicates]); // eslint-disable-line react-hooks/exhaustive-deps
 async function cleanup(){setBusy('cleanup');setError('');setMessage('');try{const d=await mutate<CleanupResult>('cleanupNarratives');setMessage(`Cleanup complete: ${d.deletedBroad||0} broad, ${d.deletedUnsupported||0} unsupported, ${d.mergedDuplicates||0} duplicates removed/merged.`);await load(0);window.dispatchEvent(new CustomEvent('front-browser-evidence-saved'));}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function remove(card:Card){if(!window.confirm(`Delete “${card.title}” from Narrative Radar? Raw evidence is kept.`))return;setBusy(card.id);setError('');try{await mutate('deleteNarrative',{id:card.id});setMessage(`Deleted ${card.title}.`);await load(offset);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function mergeInto(card:Card){if(!mergeFrom){setMergeFrom(card);setMessage('Merge mode: now choose the canonical narrative that should KEEP the combined evidence.');return;}if(mergeFrom.id===card.id){setMergeFrom(null);setMessage('Merge cancelled.');return;}if(!window.confirm(`Merge “${mergeFrom.title}” into “${card.title}”? ${card.title} will be kept.`))return;setBusy('merge');setError('');try{await mutate('mergeNarratives',{keepId:card.id,mergeId:mergeFrom.id});setMessage(`Merged ${mergeFrom.title} into ${card.title}.`);setMergeFrom(null);await load(Math.max(0,offset-((feed?.cards.length===1&&offset>0)?50:0)));window.dispatchEvent(new CustomEvent('front-browser-evidence-saved'));}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <>
  <button onClick={()=>setOpen(v=>!v)} aria-label="Open Radar Manager" style={{position:'fixed',right:20,bottom:20,zIndex:70,border:0,borderRadius:999,padding:'12px 16px',fontWeight:800,background:'#15181d',color:'#fff',boxShadow:'0 10px 30px #0005',cursor:'pointer'}}><Settings2 size={16} style={{display:'inline',verticalAlign:'-3px',marginRight:7}}/>Radar Manager</button>
  {open&&<aside style={{position:'fixed',right:20,bottom:76,zIndex:69,width:'min(620px,calc(100vw - 28px))',maxHeight:'82vh',overflow:'auto',background:'#101216',color:'#f5f5f5',border:'1px solid #ffffff22',borderRadius:18,padding:18,boxShadow:'0 24px 60px #0009'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><strong>Narrative Radar Manager</strong><div style={{fontSize:12,opacity:.65}}>Search, page through, clean, delete or merge radar topics.</div></div><button onClick={()=>setOpen(false)} aria-label="Close" style={{background:'none',border:0,color:'inherit'}}><X/></button></div>
   <div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><div style={{display:'flex',gap:6,flex:'1 1 280px'}}><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load(0);}} placeholder="Search narratives…" style={{flex:1,padding:'9px 10px',borderRadius:9,border:'1px solid #ffffff22',background:'#171a20',color:'inherit'}}/><button onClick={()=>void load(0)} disabled={!!busy}><Search size={15}/></button></div><button onClick={()=>void cleanup()} disabled={!!busy}>{busy==='cleanup'?'Cleaning…':'Clean legacy'}</button></div>
   <div style={{display:'flex',gap:14,marginTop:9,fontSize:12}}><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Show archived</label><label><input type="checkbox" checked={duplicates} onChange={e=>setDuplicates(e.target.checked)}/> Show duplicates</label></div>
   {mergeFrom&&<div style={{marginTop:10,padding:9,border:'1px solid #ffcc6655',borderRadius:9,fontSize:12}}>Merge source: <b>{mergeFrom.title}</b>. Click Merge on the narrative you want to KEEP.</div>}
   {message&&<div style={{marginTop:10,padding:9,borderRadius:9,background:'#d5ff481a',fontSize:12}}>{message}</div>}{error&&<div style={{marginTop:10,padding:9,borderRadius:9,background:'#ff52521a',fontSize:12}}>{error}</div>}
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:12,fontSize:12,opacity:.75}}><span>{feed?`${feed.page.total} matching narratives · page ${pageNumber}`:'Loading…'}</span><span>50 per page</span></div>
   {(feed?.cards||[]).map(card=><div key={card.id} style={{marginTop:9,padding:10,border:'1px solid #ffffff18',borderRadius:10}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b>{card.title}</b><div style={{fontSize:11,opacity:.65,marginTop:2}}>{card.stage} · {card.authors} recent creators · {card.platforms.join(' + ')||'social'}{card.duplicateIds?.length?` · ${card.duplicateIds.length} hidden duplicate${card.duplicateIds.length===1?'':'s'}`:''}</div>{card.relatedContexts?.length?<div style={{fontSize:11,opacity:.78,marginTop:4}}>Related: {card.relatedContexts.slice(0,4).map(x=>x.title).join(' · ')}</div>:null}</div><div style={{display:'flex',gap:5,flexShrink:0}}><button title="Merge duplicate" onClick={()=>void mergeInto(card)} disabled={!!busy}><Merge size={14}/></button><button title="Delete narrative" onClick={()=>void remove(card)} disabled={!!busy}><Trash2 size={14}/></button></div></div></div>)}
   {feed&&!feed.cards.length&&<div style={{padding:24,textAlign:'center',opacity:.6}}>No narratives match these filters.</div>}
   {feed&&<div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><button disabled={!!busy||offset===0} onClick={()=>void load(Math.max(0,offset-feed.page.limit))}><ChevronLeft size={14} style={{display:'inline',verticalAlign:'-2px'}}/> Previous</button><button disabled={!!busy||!feed.page.hasMore} onClick={()=>void load(feed.page.nextOffset??offset)}>Next <ChevronRight size={14} style={{display:'inline',verticalAlign:'-2px'}}/></button></div>}
   <small style={{display:'block',opacity:.55,marginTop:10}}>Delete/cleanup removes radar groupings and derived coin matches, not the underlying saved social evidence. Manual narratives are never removed by Clean legacy.</small>
  </aside>}
 </>;
}
