import {batches, type Signal} from './domain';
import {fetchJson,searchCoins} from './providers';
export type Evidence={id:string;platform:'X'|'TikTok';author:string;url:string;content:string;published:number|null;views:number|null;likes:number|null;provenance:string};
const normalize=(s:string)=>s.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
export function phraseMatch(text:string,phrase:string){return (' '+normalize(text)+' ').includes(' '+normalize(phrase)+' ');}
export function tiktokUrl(raw:string){const u=new URL(raw);if(u.protocol!=='https:'||!['www.tiktok.com','tiktok.com'].includes(u.hostname)||u.username||u.password||u.port||!/^\/@[a-zA-Z0-9_.]+\/video\/\d{10,25}$/.test(u.pathname))throw Error('Use the full https://www.tiktok.com/@creator/video/… link. Short links and other hosts are not accepted.');return 'https://www.tiktok.com'+u.pathname;}
export function automaticKeys(content:string){const ignore=new Set(['fyp','viral','foryou','foryoupage','trending','breaking','news','meme','memes']);const tags=[...content.matchAll(/#([\p{L}\p{N}_]{3,40})/gu)].map(m=>m[1]).filter(t=>!ignore.has(t.toLowerCase()));const names=[...content.matchAll(/\b[A-Z][a-z]{2,20}(?:\s+[A-Z][a-z]{2,20}){1,2}\b/g)].map(m=>m[0]).filter(t=>!['Read More','Breaking News','Watch This'].includes(t));return [...new Set([...tags,...names])].slice(0,8);}
export async function saveEvidence(db:D1Database,owner:string,e:Evidence,at=Date.now()){
 await db.batch([db.prepare('INSERT INTO evidence(owner,id,platform,author,url,content,published,first_seen,last_seen,provenance) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(owner,id) DO UPDATE SET content=excluded.content,last_seen=excluded.last_seen').bind(owner,e.id,e.platform,e.author,e.url,e.content,e.published,at,at,e.provenance),db.prepare('INSERT INTO observations(owner,id,observed,views,likes) VALUES(?,?,?,?,?) ON CONFLICT DO NOTHING').bind(owner,e.id,at,e.views,e.likes)]);
 for(const key of automaticKeys(e.content)){await db.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?) ON CONFLICT DO NOTHING').bind(owner,'auto:'+normalize(key),key,JSON.stringify([key]),at).run();}
 const ns=await db.prepare('SELECT id,aliases FROM narratives WHERE owner=? ORDER BY created DESC LIMIT 500').bind(owner).all<{id:string;aliases:string}>();
 const links=ns.results.filter(n=>JSON.parse(n.aliases).some((a:string)=>phraseMatch(e.content,a))).map(n=>db.prepare('INSERT INTO evidence_links(owner,narrative,evidence,reason) VALUES(?,?,?,?) ON CONFLICT DO NOTHING').bind(owner,n.id,e.id,'Caption/name/hashtag phrase match; association unverified'));
 if(links.length)await db.batch(links);
}
export async function addNarrative(db:D1Database,owner:string,title:string,aliases:string[]){if(!title.trim()||title.length>100)throw Error('Enter a narrative title of 1–100 characters.');const terms=[...new Set([title,...aliases].map(s=>s.trim()).filter(Boolean))];if(terms.length>12||terms.some(t=>t.length<3||t.length>100))throw Error('Use up to 12 phrases, each 3–100 characters.');const id=crypto.randomUUID();await db.prepare('INSERT INTO narratives(owner,id,title,aliases,created) VALUES(?,?,?,?,?)').bind(owner,id,title,JSON.stringify(terms),Date.now()).run();const es=await db.prepare('SELECT id,content FROM evidence WHERE owner=? ORDER BY last_seen DESC LIMIT 1000').bind(owner).all<{id:string;content:string}>();const links=es.results.filter(e=>terms.some(t=>phraseMatch(e.content,t))).map(e=>db.prepare('INSERT INTO evidence_links(owner,narrative,evidence,reason) VALUES(?,?,?,?) ON CONFLICT DO NOTHING').bind(owner,id,e.id,'User-defined alias match'));if(links.length)await db.batch(links);return id;}
export async function inboxTikTok(db:D1Database,owner:string,url:string){const canonical=tiktokUrl(url);const data=await fetchJson('https://www.tiktok.com/oembed?url='+encodeURIComponent(canonical));if(typeof data.title!=='string'||typeof data.author_name!=='string')throw Error('TikTok did not return valid video metadata. Nothing was saved.');const id='tiktok:'+canonical.split('/').pop();await saveEvidence(db,owner,{id,platform:'TikTok',author:canonical.split('/')[3],url:canonical,content:data.title.slice(0,8000),published:null,views:null,likes:null,provenance:'TikTok oEmbed · submitted URL · no engagement metrics'});return {id,title:data.title};}
export async function narrativeFeed(db:D1Database,owner:string){const rows=await db.prepare(`SELECT n.id,n.title,n.aliases,n.created,e.id AS evidence_id,e.platform,e.author,e.url,e.content,e.published,e.first_seen,e.last_seen,e.provenance,l.reason FROM narratives n JOIN evidence_links l ON n.owner=l.owner AND n.id=l.narrative JOIN evidence e ON e.owner=l.owner AND e.id=l.evidence WHERE n.owner=? ORDER BY e.last_seen DESC LIMIT 1500`).bind(owner).all<any>();const grouped=new Map<string,any>();for(const r of rows.results){if(!grouped.has(r.id))grouped.set(r.id,{id:r.id,title:r.title,aliases:JSON.parse(r.aliases),created:r.created,evidence:[]});grouped.get(r.id).evidence.push(r);}
 const now=Date.now();const cards=[...grouped.values()].map(n=>{const recent=n.evidence.filter((e:any)=>e.first_seen>now-3600000);const authors=new Set(recent.map((e:any)=>e.platform+':'+e.author.toLowerCase()));return{...n,authors:authors.size,platforms:[...new Set(n.evidence.map((e:any)=>e.platform))],stage:authors.size>=3?'Spreading':authors.size>=2?'Early watch':'Observed',firstSeen:Math.min(...n.evidence.map((e:any)=>e.first_seen)),lastSeen:Math.max(...n.evidence.map((e:any)=>e.last_seen))};}).sort((a,b)=>b.authors-a.authors||b.lastSeen-a.lastSeen).slice(0,50);
 const snapshots=await db.prepare('SELECT id,observed,views,likes FROM observations WHERE owner=? AND observed>? ORDER BY observed ASC LIMIT 3000').bind(owner,now-86400000).all<any>();
 for(const card of cards)for(const e of card.evidence){const ss=snapshots.results.filter(s=>s.id===e.evidence_id&&s.views!=null);const first=ss[0],last=ss.at(-1);e.views=last?.views??null;e.viewsPerMinute=first&&last&&last.observed>first.observed&&last.views>=first.views?(last.views-first.views)/((last.observed-first.observed)/60000):null;}
 const day=new Date().toISOString().slice(0,10),month=day.slice(0,7);const spend=await db.prepare('SELECT day,reserved FROM usage WHERE owner=? AND day LIKE ?').bind(owner,month+'%').all<{day:string;reserved:number}>();const cfg=await db.prepare('SELECT state,lock_until FROM collector WHERE owner=?').bind(owner).first<{state:string;lock_until:number}>();const status=cfg?JSON.parse(cfg.state):{};
 const coins=await db.prepare('SELECT narrative,mint,data,observed FROM narrative_coins WHERE owner=? ORDER BY observed DESC LIMIT 300').bind(owner).all<any>();return{cards,coins:coins.results.map(c=>({...c,data:JSON.parse(c.data)})),at:now,budget:{dayUsed:spend.results.find(r=>r.day===day)?.reserved??0,monthUsed:spend.results.reduce((s,r)=>s+r.reserved,0),dayLimit:500000,monthLimit:15000000},collector:{status:status.status??'Not scanned',lastRun:status.lastRun??null,batches:status.groups?.length??0,pendingPages:(status.groups??[]).filter((g:any)=>g.next).length},note:'Stages use newly observed distinct platform accounts within one hour; reposts may be coordinated. Phrase grouping is heuristic, not semantic video analysis. Counts are bounded to recent stored evidence.'};}
// Reserve worst-case read cost before every request. No user expansions: only post reads.
const PAGE=20,COST=5000,DAY_LIMIT=500000,MONTH_LIMIT=15000000;
export async function scanXBounded(db:D1Database,owner:string,token:string,accounts:string[]){
 const now=Date.now(),lease=crypto.randomUUID();await db.prepare('INSERT INTO collector(owner,state,lock_until,lock_id) VALUES(?,?,0,?) ON CONFLICT DO NOTHING').bind(owner,'{}','').run();
 const lock=await db.prepare('UPDATE collector SET lock_until=?,lock_id=? WHERE owner=? AND lock_until<? RETURNING state').bind(now+120000,lease,owner,now).first<{state:string}>();if(!lock)throw Error('An X scan is already running.');const state:any=JSON.parse(lock.state);try{
 if(state.lastRun&&now-state.lastRun<60000)throw Error('Wait one minute between scans.');
 const keys=batches([...new Set(accounts.map(a=>a.toLowerCase()))].sort()).map(b=>b.join(','));const old=state.groups??[];state.groups=keys.map(k=>old.find((g:any)=>g.key===k)??{key:k,checked:0,since:null,next:null,start:null,end:null,newest:null});const group=[...state.groups].sort((a,b)=>a.checked-b.checked)[0];if(!group)throw Error('Configure at least one X handle.');
 const day=new Date(now).toISOString().slice(0,10),month=day.slice(0,7);await db.prepare('INSERT INTO usage(owner,day,reserved) VALUES(?,?,0) ON CONFLICT DO NOTHING').bind(owner,day).run();
 const reserved=await db.prepare(`UPDATE usage SET reserved=reserved+? WHERE owner=? AND day=? AND reserved+?<=? AND (SELECT COALESCE(SUM(reserved),0) FROM usage WHERE owner=? AND day LIKE ?)+?<=? RETURNING reserved`).bind(PAGE*COST,owner,day,PAGE*COST,DAY_LIMIT,owner,month+'%',PAGE*COST,MONTH_LIMIT).first();
 if(!reserved){state.status='Paused: daily/monthly read budget reached';throw Error(state.status);}
 if(!group.next){group.end=new Date(now-30000).toISOString();group.start=group.since?null:new Date(now-6*3600000).toISOString();group.newest=group.since;}
 // Persist the window before network access so retries never silently skip a page.
 state.lastRun=now;state.status='Request reserved';await db.prepare('UPDATE collector SET state=? WHERE owner=? AND lock_id=?').bind(JSON.stringify(state),owner,lease).run();
 const params=new URLSearchParams({query:'('+group.key.split(',').map((a:string)=>'from:'+a).join(' OR ')+') -is:retweet',max_results:String(PAGE),'tweet.fields':'author_id,created_at,public_metrics,entities',end_time:group.end});if(group.since)params.set('since_id',group.since);else params.set('start_time',group.start);if(group.next)params.set('next_token',group.next);
 const data=await fetchJson('https://api.x.com/2/tweets/search/recent?'+params,token);
 if(data.errors?.length||(!Array.isArray(data.data)&&data.meta?.result_count!==0))throw Error('X returned an incomplete response; cursor retained.');const posts=data.data??[];if(posts.length>PAGE||posts.some((p:any)=>!/^\d+$/.test(p.id??'')||typeof p.text!=='string'||!p.author_id))throw Error('X returned invalid posts; cursor retained.');
 for(const p of posts){const expanded=(p.entities?.urls??[]).map((u:any)=>u.expanded_url??'').join(' ');await saveEvidence(db,owner,{id:'x:'+p.id,platform:'X',author:String(p.author_id),url:'https://x.com/i/status/'+p.id,content:(p.text+' '+expanded).slice(0,8000),published:Number.isFinite(Date.parse(p.created_at))?Date.parse(p.created_at):null,views:Number.isFinite(p.public_metrics?.impression_count)?p.public_metrics.impression_count:null,likes:Number.isFinite(p.public_metrics?.like_count)?p.public_metrics.like_count:null,provenance:'X recent search API'});if(!group.newest||BigInt(p.id)>BigInt(group.newest))group.newest=p.id;}
 group.checked=now;group.next=data.meta?.next_token??null;if(!group.next){group.since=group.newest;group.start=null;group.end=null;}state.status=group.next?'Page saved; more posts pending':'Batch saved';
 await db.prepare('UPDATE usage SET reserved=reserved-? WHERE owner=? AND day=?').bind((PAGE-posts.length)*COST,owner,day).run();
 const feed=await narrativeFeed(db,owner);const signals:Signal[]=feed.cards.map((n:any)=>({id:n.id,title:n.title,query:n.aliases[0],source:'Stored social evidence',detail:n.stage+' · '+n.authors+' recently observed accounts',url:n.evidence[0].url,evidence:n.evidence.slice(0,8).map((e:any)=>({url:e.url,text:e.content,author:e.author,views:e.views}))}));return{signals,at:now,posts:posts.length,coverage:[{source:'X · one incremental batch',ok:true}],note:'20 posts maximum per request. $0.50/day and $15/month estimated post-read limits. Additional pages and batches resume on later scans; API billing is authoritative.'};
 }catch(e){state.status=(e as Error).message;throw e;}finally{await db.prepare('UPDATE collector SET state=?,lock_until=0,lock_id=? WHERE owner=? AND lock_id=?').bind(JSON.stringify(state),'',owner,lease).run();}
}
export async function matchNarrative(db:D1Database,owner:string,id:string){const n=await db.prepare('SELECT aliases FROM narratives WHERE owner=? AND id=?').bind(owner,id).first<{aliases:string}>();if(!n)throw Error('Narrative not found');const queries=JSON.parse(n.aliases).slice(0,3);const coverage=[];for(const q of queries){const result=await searchCoins(q);coverage.push(...result.coverage);for(const c of result.coins){await db.prepare('INSERT INTO narrative_coins(owner,narrative,mint,data,observed) VALUES(?,?,?,?,?) ON CONFLICT(owner,narrative,mint) DO UPDATE SET data=excluded.data,observed=excluded.observed').bind(owner,id,c.mint,JSON.stringify({...c,matchReason:'Search candidate for '+q+'; narrative association unverified'}),Date.now()).run();}}return{coverage,queries};}
